site_name: DDataflow
site_url: https://code.getyourguide.com/DDataFlow/
repo_url: https://github.com/getyourguide/DDataFlow/
edit_uri: edit/main/docs/

theme:
  name: material
  icon:
    edit: material/pencil
    repo:  fontawesome/brands/github
  features:
    - content.action.edit



markdown_extensions:
  - pymdownx.superfences

nav:
  - 'index.md'
  - 'local_development.md'
  - 'sampling.md'
  - API Reference:
    - 'api_reference/DDataflow.md'
    - 'api_reference/DataSource.md'
    - 'api_reference/DataSources.md'
    - 'api_reference/DataSourceDownloader.md'
  - 'troubleshooting.md'
  - 'FAQ.md'

plugins:
  - search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: sphinx
            allow_inspection: true
