name: Dependabot Approve

on:
  workflow_dispatch:
  schedule:
  - cron: 0 9 * * Mon
  - cron: 0 10 * * Mon

jobs:
  auto-approve:
    name: Approve PR
    uses: getyourguide/actions/.github/workflows/dependabot-approve.yml@main
    with:
      targets: patch:all,minor:all,major:development
      pr-url: ${{ github.event.pull_request.html_url }}
  auto-merge:
    name: Auto merge
    uses: getyourguide/actions/.github/workflows/dependabot-merge.yml@main
    with:
      slack_channel: '#mlplatform-alerts'
      slack_ping_support: true
      hide_report_sections: ${{ (github.event.schedule == '0 9 * * Mon-Fri' && 'blocked,pending-approval') || ''}}
    secrets: inherit
