name: Publish python poetry package
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

permissions:
  packages: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Build and publish to pypi
        shell: bash
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          pip install poetry
          poetry config virtualenvs.create false
          poetry build
          echo "Publishing now..."
          poetry publish -u "__token__" --password "$PYPI_TOKEN" || true